name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true  # 初始化和更新子模块

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # 假设您的构建命令是 `npm run build`

    - name: Move build output to docs folder
      run: mv dist docs  # 将构建输出移动到 docs 文件夹

    - name: List files in current directory
      run: ls -la

    - name: Show .gitmodules content
      run: cat .gitmodules

    - name: Show .git/config content
      run: cat .git/config

    - name: Initialize submodules
      run: |
        git submodule init
        git submodule update --recursive

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs  # 确保这是构建输出的目录
